return {
  "akinsho/bufferline.nvim",
  event = "VeryLazy",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  version = "*",
  opts = {
    options = {
      mode = "tabs",
      numbers = "ordinal",
      close_command = function(n)
        vim.api.nvim_buf_delete(n, {})
      end,
      right_mouse_command = function(n)
        vim.api.nvim_buf_delete(n, {})
      end,
      indicator = {
        style = "underline",
      },
      buffer_close_icon = "",
      modified_icon = "",
      close_icon = "",
      left_trunc_marker = "",
      right_trunc_marker = "",
      show_buffer_close_icons = true,
      show_close_icon = true,
      diagnostics = "nvim_lsp",
      diagnostics_update_in_insert = false,
      offsets = {
        {
          filetype = "NvimTree",
          text = "File Explorer",
          highlight = "Directory",
          separator = true,
        },
      },
      separator_style = "thin",
    },
    highlights = {
      fill = { bg = "NONE" },
      background = { bg = "NONE", fg = "#627E97" },
      tab = { bg = "NONE", fg = "#627E97" },
      tab_selected = { fg = "#CBE0F0", bg = "NONE", bold = false },
      buffer_selected = { fg = "#CBE0F0", bg = "NONE", bold = true, italic = false },
      buffer_visible = { fg = "#B4D0E9", bg = "NONE" },
      close_button = { fg = "#627E97", bg = "NONE" },
      close_button_selected = { fg = "#CBE0F0", bg = "NONE" },
      modified = { fg = "#E5C07B", bg = "NONE" },
      modified_selected = { fg = "#E5C07B", bg = "NONE" },
      modified_visible = { fg = "#E5C07B", bg = "NONE" },
      separator = { fg = "NONE", bg = "NONE" },
      separator_selected = { fg = "NONE", bg = "NONE" },
      indicator_selected = { fg = "NONE", bg = "NONE" },
      diagnostic = { fg = "#E06C75" },
      diagnostic_selected = { fg = "#E06C75" },
      diagnostic_visible = { fg = "#E06C75" },
      hint = { fg = "#61AFEF" },
      hint_selected = { fg = "#61AFEF" },
      hint_visible = { fg = "#61AFEF" },
      info = { fg = "#61AFEF" },
      info_selected = { fg = "#61AFEF" },
      info_visible = { fg = "#61AFEF" },
      warning = { fg = "#E5C07B" },
      warning_selected = { fg = "#E5C07B" },
      warning_visible = { fg = "#E5C07B" },
      error = { fg = "#E06C75" },
      error_selected = { fg = "#E06C75" },
      error_visible = { fg = "#E06C75" },
    },
  },
  keys = {
    { "<Tab>", "<Cmd>BufferLineCycleNext<CR>", desc = "Next tab" },
    { "<S-Tab>", "<Cmd>BufferLineCyclePrev<CR>", desc = "Prev tab" },
    { "<leader>1", "<Cmd>BufferLineGoToBuffer 1<CR>", desc = "Tab 1" },
    { "<leader>2", "<Cmd>BufferLineGoToBuffer 2<CR>", desc = "Tab 2" },
    { "<leader>3", "<Cmd>BufferLineGoToBuffer 3<CR>", desc = "Tab 3" },
    { "<leader>4", "<Cmd>BufferLineGoToBuffer 4<CR>", desc = "Tab 4" },
    { "<leader>5", "<Cmd>BufferLineGoToBuffer 5<CR>", desc = "Tab 5" },
    { "<leader>6", "<Cmd>BufferLineGoToBuffer 6<CR>", desc = "Tab 6" },
    { "<leader>7", "<Cmd>BufferLineGoToBuffer 7<CR>", desc = "Tab 7" },
    { "<leader>8", "<Cmd>BufferLineGoToBuffer 8<CR>", desc = "Tab 8" },
    { "<leader>9", "<Cmd>BufferLineGoToBuffer 9<CR>", desc = "Tab 9" },
  },
}
