backend = "xrender";
vsync = true;
shadow = false;
use-damage = false;
unredir-if-possible = false;

fading = true;
fade-delta = 10;
fade-in-step = 0.02;
fade-out-step = 0.02;

animations = true;

animation-for-open-window = "fly-in";
animation-for-close-window = "fly-in";
animation-for-workspace-switch-in = "slide-left";
animation-for-workspace-switch-out = "slide-right";

animation-for-startup = "fly-in";
animation-for-minimize = "fly-in";

transition-length = 400;
transition-pow-x = 0.02;
transition-pow-y = 0.02;
transition-pow-w = 0.1;
transition-pow-h = 0.1;

transition-length = 350;

inactive-opacity = 1.0;
active-opacity = 1.0;

opacity-rule = [
  "90:class_g = 'Alacritty'",
  "85:class_g = 'fzf-filebrowser'",
  "80:class_g = 'dev.warp.Warp'",
  "90:class_g = 'i3bar'",
  "90:class_g = 'i3status'",
  "90:class_g = 'Polybar'",
];

detect-client-opacity = true;
detect-transient = true;

wintypes:
{
  dock = { opacity = 0.9; };
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 0.8; };
  dropdown_menu = { opacity = 0.8; };
};
