[ env ]
TERM = "xterm-256color"

[window]
# padding.x = 10
padding = { x = 10, y = 10 }
opacity = 0.8
blur = false

decorations = "none"

[font]
# normal.family = "Hack Nerd Font"
normal.family = "JetBrains Mono"
size = 10

[[keyboard.bindings]]
action = "Paste"
key = "p"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "c"
mods = "Alt"

[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
chars = "\u001b[D"  

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u001b[B" 

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u001b[A"

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[C"

[general]
import = [
    "./themes/coolnight.toml"
]

#for video
# size = 35.0

